services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6.7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      # For persistence of the MariaDB data
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    build: .
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

  phpmyadmin:
    image: bitnami/phpmyadmin
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb

volumes:
  moodle_data:
  moodledata_data:
  mariadb_data:
